#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#include "tusb_option.h"

#define CFG_TUSB_MCU OPT_MCU_RP2040
#define CFG_TUSB_OS OPT_OS_PICO
#define CFG_TUSB_RHPORT0_MODE OPT_MODE_DEVICE
#define CFG_TUSB_RHPORT1_MODE OPT_MODE_DISABLED

#define CFG_TUD_ENABLED 1
#define CFG_TUD_HID 1
#define CFG_TUD_HID_EP_BUFSIZE 16

#endif
